datawarehouse2:
  outputs:
    dev:
      dbname: dbsales_ao1f
      host: dpg-cq7bupaj1k6c73955rf0-a.oregon-postgres.render.com
      pass: "yUsyOnat8aRbF1LMqyUpy6T6EwVZAsKg"
      port: 5432
      schema: public
      threads: 1
      type: postgres
      user: postgres123
  target: dev
